export { default as Navbar } from './navbar/Navbar';
export { default as Hero } from './hero/Hero';
export { default as Content } from './content/Content';
export { default as Brand } from './brand/Brand';
export { default as Work } from './work/Work';
export { default as Footer } from './footer/Footer';
export { default as Time } from './time/Time';
export { default as Service } from './service/Service';
export { default as ScrollToTopButton } from './scrollToTopButton/ScrollToTopButton';